POST http://localhost:3000/authentication/authorize HTTP/1.1
content-type: application/json

{
    "email": "sylvain.romiguier@gmail.com",
    "password": "Hyperion30#"
}
###
GET http://localhost:3000/authentication/me HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZTgwOGEwOS05NmNlLTQ2NGQtYTA2OC03YTBmZDA0NDVlYmUiLCJpYXQiOjE2NjcyMDkzODF9.U9KBjlWNdMfi9oWAaa23tzCXMzQYF3RoxPlhb6AQJ8ILuTb-rOPDCO7FkXYRJT82_NWVIFsLX1NEhxvEt-12MGmpgPHxkXNEze4CgJ-toQPcHRb8OKDEqbPdjJ4VZQolBIrjxd5XI1PR10Vwq66wh0grmsebrr8u_czIy_BmcZhpInCP2MP5cpaVkf6onAdB4sxjG9XENr8eYwcxoUBIUXIsnl1EQ9V-I7d4augIz8uX10me2B8P4xoBEQguXdK_e_CM6tyznrKvA3fIski0RO66_qRzJRqQ6Ojy8ds9IjbBqjCPmf5jkupDb22dLuxhxY3wWvwTpWLWk9Cqp7vEdNrtLdhV1G2SJ-5p0G44u_o6C09O99jpvhcTVdEZsLLSa1kenUWExGBi5ttB7a-Ej9byCgMahc7lKsk4xCn8I_KqsH5OvOgcZpxiFDX4tB4_GN9y842n8_1GkoGp4wW2mSIEZEwgbyYpjUiTbRsG8P1Y1QHLun_Q9qet_2rV8G6b0cA1QjGXUgtQJQpA6yFVVh6IMSQZ-0IfvUhDiHWhEjoCF6MNBCqCRKZEz-8QK9VMonlva4QGccGkXqxbIUlFs9sayFiFtMSrOqiUUQ2WpGcyADqszJR95TwNUL9YncpsAZuEoxRoLVnnlzchdBnvsQiWcRj6w7eTlMLaw4LU7Hc
