POST http://localhost:3000/authentication/authorize HTTP/1.1
content-type: application/json

{
    "email": "sromiguier-ext@kpler.com",
    "password": "MyPrettyPassword34#"
}
###
GET http://localhost:3000/authentication/me HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZTgwOGEwOS05NmNlLTQ2NGQtYTA2OC03YTBmZDA0NDVlYmUiLCJpYXQiOjE2Njc5MDg3NTJ9.DfJ6pLlNEC2q7oPXw5OWb0sfKmMNPPcScLcTvJ8-ztTcxpt98v1eyZbXqF9PkhPJ_0bzWoa6zXI9YTyaX5sVoFNT5wphy9US-UGkj7XIfMlRwI8bj60hMFRbF0Qem2s1oAXvqM79ObJQEaV7tkMJpL-Dlp0Tj8P1igA2XQqkJpcXBSyuIexuSYsYcSLpIXGp0ATjOHy6VyoYjZEmw8DKBs-ibJROISFlyIQ1mqujUmSSE_-d6qdzT1HREsIrxnMPgo00bilVvhUuWnriWpCkKsFcE0WoP1h7DCv0lI9tAp1zHMGwvfFBNm7e9Ko9ETMz5q45TSeVZVvp5QvLXs4zC-V_GfqW6txzWDkqbT2Rh2xKT-5_m4DibG28DHk2mlJKWwjL5f2KT4f841hStLNLjetkGw_3rBaLL_3-JyhFdRq1-D4Kag3fNscHyOs4a6z_i1_WWD_f-c0hXRt-el85P3xH9clozOXziJ4jiw8w68goN-4UNCraOehGEaZRRguvAqxNorF4fZrcfDjX_-cK4NNpQCBYeowt483cjvQ4mIF3QCit1IwyjDM0yW-Zyf-19uIlYdYt5YTZ9JysvgihYHhcUI2oK8Ld2lj57YIEJl4Q5hOP96oSzfHLvjikkYVWm8Adn7HsEhFa5O8zvzqD94dAVRulnwN1iUjPO3OR1p4
